### ISSUE TITLE
Mocha examples

### ISSUE THREAD

**Issue by demisx** [Coffa/factory_girl#15]
Hi.  Are there any example on how this module can be used with mocha/chai unit tests?

**Comment by MQuy** [comment]
hi @demisx , this module is like model which helps you to create fake object. I often use like that not sure about what you want
For example, in /dashboard you fetch the array of news and you want to test that function, so you mock New model into that ajax and use mocha to test

**Comment by demisx** [comment]
@MQuy Thank you for quick reply. An example with a simple `describe/it` block in your readme would be helpful. Do FG models access the database? Do I need a test schema set up like in Rails?

**Comment by mcquackers** [comment]
@demisx your question is old, but on the off-chance you haven't resolved it:

~/project-folder/test/factories/example-factories-for-test/factory-example.js
```
    FactoryGirl.define("descriptiveFactoryModelName", function() {
      //javascript object here
      this.attribute = value;
      this.attribute2 = value2;
      etc;
    }
```


Actual test file:
~/project-folder/test/project-test-1.js:
```
  var factoryGirl = require("factory_girl");
  factoryGirl.definitionFilePaths = [__dirname + "/factories/"];
  factoryGirl.findDefinitions();
```

These are the basics required for using this version of FactoryGirl.  the definitionFilePaths requires the actual text "__dirname" for the current directory to begin in, and the entire thing must be in an array.

Once you need to call up one of your factories, you simply create a javascript object:
`var factoryGirlModel = factoryGirl.create("descriptiveFactoryModelName");`

Obviously substitute "factoryGirlModel" and "descriptiveFactoryModelName" to the relevant names you want to use.

**Comment by demisx** [comment]
@mcquackers Very nice explanation. Thank you. If my understanding is correct, the factory models are pure old javascript objects (POJOs) and do not require access to the database like rails Factory Girl.
