### ISSUE TITLE
[REQUEST] Bower installation support?

### ISSUE THREAD

**Issue by mtyeh411** [Coffa/factory_girl#16]
This looks like a great library that I can envision being a part of my everyday front-end testing stack.  I would really love if this were registered with Bower as a Bower package (as I'm sure many others would as well).

**Comment by mtyeh411** [comment]
oh nvm...i see the `module.exports` definitions for `FactoryGirl`

**Comment by MQuy** [comment]
@mtyeh411 thanks for your request. I will do it asap

**Comment by mtyeh411** [comment]
awesome. thanks @MQuy 

also please consider my pull request as well
https://github.com/Coffa/factory_girl/pull/17

**Comment by demisx** [comment]
+1

**Comment by MQuy** [comment]
done @mtyeh411
